CREATE TABLE Students(
    SID INTEGER PRIMARY KEY,
    Name VARCHAR2(40) NOT NULL,
    Major VARCHAR2(40) NOT NULL
);

CREATE TABLE Projects(
    PID INTEGER PRIMARY KEY,
    P_Name VARCHAR2(40)
);

CREATE TABLE Courses(
    CID INTEGER PRIMARY KEY,
    C_Name VARCHAR2(40)
);

CREATE TABLE Members(
    PID INTEGER,
    SID INTEGER,
    PRIMARY KEY(PID, SID),
    FOREIGN KEY(PID)
        REFERENCES Projects(PID),
    FOREIGN KEY(SID)
        REFERENCES Students(SID)
);

CREATE TABLE Enrollments(
    CID INTEGER,
    SID INTEGER,
    PRIMARY KEY(CID, SID),
    FOREIGN KEY(CID)
        REFERENCES Courses(CID),
    FOREIGN KEY(SID)
        REFERENCES Students(SID)
);
